// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import * as dotenv from 'dotenv';
import { defineConfig, env } from 'prisma/config';

dotenv.config();

export default defineConfig({
  // Путь до schema.prisma (от корня проекта)
  schema: 'src/prisma/schema.prisma',

  // Путь до папки с миграциями
  migrations: {
    path: 'src/prisma/migrations',
  },

  // URL подключения к БД — берётся из .env
  // env() — это helper Prisma 7, аналог process.env, но безопасный для CLI
  datasource: {
    url: env('DATABASE_URL'),
  },
});
